import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import mypic from '../styles/notebook.png';
import del from '../styles/close.png';
import { useState } from 'react';


export default function Home() {
  const [userInput, setUserInput] = useState('');
  const [todoList, setTodoList] = useState([]);

  const handleChange = (e) => {
    e.preventDefault();
    setUserInput(e.target.value);
    console.log(userInput);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setTodoList([
      { id: todoList.length + 1, title: userInput, status: 'todo' },
      ...todoList,
    ]);

    setUserInput('');
  };

  const handleDelete = (todo) => {
    const updatedArr = todoList.filter(
      (todoItem) => todoList.indexOf(todoItem) != todoList.indexOf(todo)
    );
    setTodoList(updatedArr);
  };

  const changeTodoStatus = (id, reqStatus) => {
    const updatedTodoList = todoList.map((todo) =>
      todo.id === id
        ? {
            ...todo,
            status:
              reqStatus === 'progress'
                ? todo.status === 'progress'
                  ? 'todo'
                  : 'progress'
                : reqStatus === 'done'
                ? todo.status === 'done'
                  ? 'todo'
                  : todo.status === 'todo'
                  ? 'done'
                  : todo.status === 'progress'
                  ? reqStatus
                  : 'todo'
                : todo.status === 'done'
                ? 'todo'
                : todo.status === 'progress'
                ? 'done'
                : 'done',
          }
        : todo
    );
    setTodoList(updatedTodoList);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>ToDo-List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>ToDo-List</h1>

        <Image src={mypic} width='200px' height='200px' />

        <p className={styles.description}>Simplify and organize your life</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <form>
              <input
                type='text'
                value={userInput}
                className={styles.field}
                placeholder='Enter the To-Do Item'
                onChange={handleChange}
              />
              <button className={styles.button1} onClick={handleSubmit}>
                <span>Submit</span>
              </button>
            </form>
            <div>
              {/* {
                    todoList.length >=1 ? todoList.map((todo, idx) => {
                        return <p className={styles.list} key={idx}><button className={styles.closebtn} onClick = {(e) =>{
                          e.preventDefault()
                          handleDelete(todo)
                      }}>X</button> {todo}</p>
                      
                    })
                    :'Enter a Todo Item'
                } */}
              {todoList.length >= 1
                ? todoList.map((todo, idx) => {
                    return (
                      <div className={styles.list} key={idx}>
                        <div>
                          <input
                            onClick={() =>
                              changeTodoStatus(todo.id, todo.status)
                            }
                            checked={todo.status === 'done'}
                            type={'checkbox'}
                          />{' '}
                          Done
                        </div>
                        <div>
                          <input
                            onClick={() =>
                              changeTodoStatus(todo.id, 'progress')
                            }
                            checked={todo.status === 'progress'}
                            type={'checkbox'}
                          />{' '}
                          Progress
                        </div>
                        <div
                          className={
                            todo.status === 'done'
                              ? styles.doneItem
                              : todo.status === 'progress'
                              ? styles.progressItem
                              : styles.todoItem
                          }
                        >
                          {todo.title}
                        </div>
                        <button
                          className={styles.closebtn}
                          onClick={(e) => {
                            e.preventDefault();
                            handleDelete(todo);
                          }}
                        >
                          X
                        </button>{' '}
                      </div>
                    );
                  })
                : 'Enter a Todo Item'}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
